### ISSUE TITLE
ETHBerlin Olympia UI/UX feedback

### ISSUE THREAD

**Issue by mariapaulafn** [gnosis/pm-trading-ui#506]
The way final results are displayed is a tad misleading, see screenshot. 
I'd add colors to all, regardless of %
<img width="892" alt="bildschirmfoto 2018-09-17 um 11 34 30" src="https://user-images.githubusercontent.com/27913589/45699999-bf4a1c00-bb6b-11e8-9beb-5dd23f6aea74.png">

**Comment by mariapaulafn** [comment]
Also, i am wondering why it displays 0% instead of the percentage of votes/bids they got on the PM

**Comment by andre-meyer** [comment]
Hi @mariapaulafn!

Sorry for the late answer! 🙈Thank you for your feedback! We'll definitely improve the UI on the bar-chart, it's part of an ongoing process to improve the UI/UX on the market detail pages. We'll mention you in a ticket once we're working on it

As for the display of the 0% instead of votes/bids, this is actually not directly possible, because of how the prediction market algorithm works:
Users who participate in Prediction Markets buy outcome-tokens for each of the individual outcomes and the price for those outcomes is dependant on the current prediction, that means that when an outcome is at 0% (or close to, it's probably a really long decimal number in the market you mentioned) you get a lot of outcome tokens for the same price and vise-versa on an outcome with a lot of probability, the outcome tokens are more expensive. This way we don't financially incentivize those who invest in the already popular outcome. There is no concept of "users who bought this outcome" unfortunately.
What we can do however, is show a more detailed summary of how the percentages come to be. (e.g. showing the number of outcome tokens sold, what their individual prices are and so on.) We'll also let you know when we start improving that topic specifically! Thanks again 👍
